micronaut:
  application:
    name: static-server-oidc
  server:
    port: ${SERVER_PORT:80}
  router:
    static-resources:
      assets:
        mapping: /**
        paths: file:${PUBLIC_HTML_ROOT}
  security:
    enabled: true
    authentication: idtoken
    oauth2:
      clients:
        default:
          client-id: ${OAUTH2_CLIENT_ID}
          client-secret: ${OAUTH2_CLIENT_SECRET}
          openid:
            issuer: ${OIDC_ISSUER_URL}
            authorization:
              prompt: login
      callback-uri: ${OAUTH2_CALLBACK_URL:/oauth/callback/default}
    intercept-url-map:
      - pattern: /**
        http-method: GET
        access: isAuthenticated()
    endpoints:
      logout:
        get-allowed: true
    redirect:
      unauthorized:
        url: ${UNAUTHORIZED_REDIRECT_URL:/oauth/login/default}
      login-success: ${LOGIN_SUCCESS_URL:/}